[project]
name = "dsa-python"
version = "0.1.0"
description = "This repository is for tracking my DSA journey in Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
]
